title: Nature Slice
author: Alicia Hodson
email: alicia.k.hodson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hoping to encourage more interest in the natural world, particularly little known species, through art and media.

# social links
twitter_username: NatureSliceUK # DO NOT include the @ character, or else the build will fail!
github_username:  NatureSlice # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
